import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/src/components/common/QueryProvider";
import AuthProvider from "@/src/components/common/AuthProvider";
import ReduxProvider from "@/src/components/common/ReduxProvider";
import AppContextProvider from "@/src/components/common/AppContextProvider";
import IntlProviderWrapper from "@/src/components/common/IntlProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeProvider from "@/src/components/common/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Niyom App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={inter.className}>
				<AppContextProvider>
					<ReduxProvider>
						<QueryProvider>
							<IntlProviderWrapper>
								<AuthProvider>
									<AntdRegistry>
										<ThemeProvider>{children}</ThemeProvider>
									</AntdRegistry>
								</AuthProvider>
							</IntlProviderWrapper>
						</QueryProvider>
					</ReduxProvider>
				</AppContextProvider>
			</body>
		</html>
	);
}
