import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeRegistry from "@/src/components/ThemeRegistry/ThemeRegistry";
import QueryProvider from "@/src/components/common/QueryProvider";
import AuthProvider from "@/src/components/common/AuthProvider";
import ReduxProvider from "@/src/components/common/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={inter.className}>
				<ReduxProvider>
					<QueryProvider>
						<AuthProvider>
							<ThemeRegistry>{children}</ThemeRegistry>
						</AuthProvider>
					</QueryProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
